### ISSUE TITLE
Navbar not hidden by .sweet-overlay [FIXED]

### ISSUE THREAD

**Issue by philippeboyd** [lipis/bootstrap-sweetalert#8]
When using a fixed bootstrap .navbar / navbar-fixed-top, the default css for the sweet-overlay won't hide the navbar.

Simply add/ or change CSS

``` css
.sweet-overlay{
    z-index: 1500; /* default value is 1000 */
}
```
